### ISSUE TITLE
eslint-plugin-import breaks if package.json is not in parent directory to the linted code

### ISSUE THREAD

**Issue by trumko** [import-js/eslint-plugin-import#2510]
After updating `eslint-plugin-import `from` 2.22.1` to `2.23.0` or higher the `eslint-plugin-import` breaks with warning:

`ERROR in [eslint] The "path" argument must be of type string. Received null`

After some investigation it looks like the reason is in the file structure, when `package.json` file is not in the parent directory to the linted code:

```
myProject
├── build
  ├──  node_modules # is not in the parent directory to  source folder
  ├──  package.json
  └──  [webpack.config.js, .eslintrc.js and other config files]
└── source
  └── modules #.js files, which should be linted
```

Interestingly, when I create a `package.json` file (which contains only empty `{}`) in the `myProject` folder, everything works as expected.

My .eslintrc.js:

```
const path = require('path');

module.exports = {
  parser: 'babel-eslint',
  extends: [
    'plugin:react-hooks/recommended'
  ],
  settings: {
    'import/resolver': {
      webpack: {
        config: path.join(__dirname, 'webpack.config.js')
      },
    },
    react: {
      version: 'latest',
    },
  },
  globals: {},
  env: {
    browser: true,
    es6: true,
  },
  root: true,
  rules: {
    // list of modified rules
  },
};
```

**Comment by JounQin** [comment]
Can you provide a minimal but runnable reproduction?

**Comment by trumko** [comment]
I just created minimal [reproduction](https://github.com/trumko/eslintMinimalReproduction), which is based on [this boilerplate](https://github.com/jpggvilaca/webpack-boilerplate).

1. Download repo
2. Go to `/build` folder
3. Run `npm install`
4. Run `npm start`

You should see the next error:
```
ERROR in [eslint] The "path" argument must be of type string. Received null
Occurred while linting [folder]\webpack-boilerplate-master\app\index.js:1
Rule: "import/no-extraneous-dependencies"
```

**Comment by JounQin** [comment]
@trumko Thanks for reproduction first, I'll take a look when I'm free.

**Comment by miartysh-cartera** [comment]
@JounQin `eslint-webpack-plugin` contributors [claim](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/177) the issue is related to the `eslint-plugin-import`, can you double-check please?

**Comment by trumko** [comment]
@JounQin `eslint-webpack-plugin` contributors [claim](https://github.com/webpack-contrib/eslint-webpack-plugin/issues/177) the issue is related to the `eslint-plugin-import`, can you double-check please?

**Comment by JounQin** [comment]
@trumko Then can you simply the reproduction that use eslint directly instead of relying on eslint-webpack-plugin?

**Comment by trumko** [comment]
@JounQin I updated the minimal [runnable reproduction](https://github.com/trumko/eslintIssue/tree/main) (just to be sure the lates package versions are used). The issue is still reproducible, the steps to reproduce are the same as in initial comment.

I also replaced the webpack resolver with node resolver (I assume we need some resolver in any case to trigger proper eslint import check):
```
  settings: {
    // 'import/resolver': {
    //   webpack: {
    //     config: path.join(__dirname, 'webpack.config.js')
    //   }
    // },
    'import/resolver': {
      node: {
          paths: ['../app', 'node_modules'],
      },
    },
  },
```

and as you recommended used it directly running `npx eslint ../app/* -c ./.eslintrc.js` and got the same error:

```
$ npx eslint ../app/* -c ./.eslintrc.js
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.

Oops! Something went wrong! :(

ESLint: 8.56.0

TypeError: The "path" argument must be of type string. Received null
Occurred while linting D:\test\app\index.js:1
Rule: "import/no-extraneous-dependencies"
    at validateString (node:internal/validators:162:11)
    at dirname (node:path:658:5)
    at getFilePackagePath (D:\ttt\build\node_modules\eslint-plugin-import\lib\core\packagePath.js:14:641)
    at getContextPackagePath (D:\ttt\build\node_modules\eslint-plugin-import\lib\core\packagePath.js:14:420)
    at isExternalPath (D:\ttt\build\node_modules\eslint-plugin-import\lib\core\importType.js:127:1567)
    at typeTest (D:\ttt\build\node_modules\eslint-plugin-import\lib\core\importType.js:127:2648)
    at resolveImportType (D:\ttt\build\node_modules\eslint-plugin-import\lib\core\importType.js:127:2875)
    at reportIfMissing (D:\ttt\build\node_modules\eslint-plugin-import\lib\rules\no-extraneous-dependencies.js:187:50)
    at commonjs (D:\ttt\build\node_modules\eslint-plugin-import\lib\rules\no-extraneous-dependencies.js:294:9)
    at checkSourceValue (D:\ttt\build\node_modules\eslint-module-utils\moduleVisitor.js:30:5)
    at checkSource (D:\ttt\build\node_modules\eslint-module-utils\moduleVisitor.js:35:5)
    at ruleErrorHandler (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1076:28)
    at D:\ttt\build\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (D:\ttt\build\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (D:\ttt\build\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (D:\ttt\build\node_modules\eslint\lib\linter\node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (D:\ttt\build\node_modules\eslint\lib\linter\node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (D:\ttt\build\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:803:23)
    at D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1111:32
    at Array.forEach (<anonymous>)
    at runRules (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1106:15)
    at Linter._verifyWithoutProcessors (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1355:31)
    at Linter._verifyWithConfigArray (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1807:21)
    at Linter.verify (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:1437:65)
    at Linter.verifyAndFix (D:\ttt\build\node_modules\eslint\lib\linter\linter.js:2068:29)
    at verifyText (D:\ttt\build\node_modules\eslint\lib\cli-engine\cli-engine.js:254:48)
    at CLIEngine.executeOnFiles (D:\ttt\build\node_modules\eslint\lib\cli-engine\cli-engine.js:834:28)
    at ESLint.lintFiles (D:\ttt\build\node_modules\eslint\lib\eslint\eslint.js:551:23)
    at Object.execute (D:\ttt\build\node_modules\eslint\lib\cli.js:421:36)
    at async main (D:\ttt\build\node_modules\eslint\bin\eslint.js:152:22)
```

Another one reason why I think issue could be on `eslint-plugin-import` side is that I faced it only after updating the `eslint-plugin-import` package, it was not respoducible in `2.22.1`
