### ISSUE TITLE
`newline-after-import` not accepts `considerComments` prop

### ISSUE THREAD

**Issue by slice312** [import-js/eslint-plugin-import#2522]
Invalid property `considerComments`

Rule in my config:
` "import/newline-after-import": ["warn", {count: 2, considerComments: false}],`

Error log:
```
Oops! Something went wrong! :(
ESLint: 8.21.0
Error: .eslintrc.cjs:
        Configuration for rule "import/newline-after-import" is invalid:
        Value {"count":2,"considerComments":false} should NOT have additional properties.

      at ConfigValidator.validateRuleOptions (D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2027:23)
      at D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2082:18
      at Array.forEach (<anonymous>)
      at ConfigValidator.validateRules (D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2079:34)
      at ConfigValidator.validateConfigArray (D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2205:18)
      at CascadingConfigArrayFactory._finalizeConfigArray (D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3947:23)
      at CascadingConfigArrayFactory.getConfigArrayForFile (D:\Projects\react\ZeonBonusMarket\client\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3753:21)
      at FileEnumerator._iterateFilesRecursive (D:\Projects\react\ZeonBonusMarket\client\node_modules\eslint\lib\cli-engine\file-enumerator.js:446:49)
      at _iterateFilesRecursive.next (<anonymous>)
      at FileEnumerator.iterateFiles (D:\Projects\react\ZeonBonusMarket\client\node_modules\eslint\lib\cli-engine\file-enumerator.js:297:49)
 
  ```

**Comment by ljharb** [comment]
That's because it hasn't been released yet.

On Github, you always have to check the docs under a tagged release, not on main/master.

**Comment by slice312** [comment]
ok, sry

**Comment by Samuel-Therrien-Beslogic** [comment]
@ljharb I have 2.27.5 installed and still get the error
`npm list eslint-plugin-import`
```
├─┬ eslint-import-resolver-typescript@3.5.5
│ └── eslint-plugin-import@2.27.5 deduped
└── eslint-plugin-import@2.27.5
```

```json
rules: {
  "import/newline-after-import": [
    "error",
    { "considerComments ": true }
  ],
}
```
