### ISSUE TITLE
Fail to load custom resolver with Yarn PnP and ESM

### ISSUE THREAD

**Issue by Toilal** [import-js/eslint-plugin-import#2650]
I'm running an ESM project with Yarn v3 and [PnP enabled](https://yarnpkg.com/features/pnp). In such a configuration, eslint-plugin-import can't resolve module from [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript).

```
Oops! Something went wrong! :(

ESLint: 8.30.0

EslintPluginImportResolveError: unable to load resolver "typescript".
Occurred while linting /home/toilal/projects/carbon-saver/platform.carbon-saver/packages/directus-codegen.carbon-saver/src/context.ts:1
Rule: "import/namespace"
    at requireResolver (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-module-utils-virtual-6500b5fbef/0/cache/eslint-module-utils-npm-2.7.3-ccd32fe6fd-77048263f3.zip/node_modules/eslint-module-utils/resolve.js:186:17)
    at fullResolve (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-module-utils-virtual-6500b5fbef/0/cache/eslint-module-utils-npm-2.7.3-ccd32fe6fd-77048263f3.zip/node_modules/eslint-module-utils/resolve.js:137:22)
    at Function.relative (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-module-utils-virtual-6500b5fbef/0/cache/eslint-module-utils-npm-2.7.3-ccd32fe6fd-77048263f3.zip/node_modules/eslint-module-utils/resolve.js:83:10)
    at remotePath (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:801:379)
    at captureDependency (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:803:380)
    at /home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:811:107
    at Array.forEach (<anonymous>)
    at ExportMap.parse (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:806:427)
    at ExportMap.for (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:797:201)
    at ExportMap.get (/home/toilal/projects/carbon-saver/platform.carbon-saver/.yarn/__virtual__/eslint-plugin-import-virtual-2ccad592e8/0/cache/eslint-plugin-import-npm-2.26.0-959fe14a01-0bf77ad803.zip/node_modules/eslint-plugin-import/lib/ExportMap.js:791:463)
```

With the folowing config

```js
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    sourceType: 'module'
  },
  extends: [
    'plugin:import/recommended',
    'plugin:import/typescript'
  ],
  settings: {
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true
      }
    }
  }
}
```

As a workaround, I have to disable PnP from yarn using this setting in `.yarnrc.yml`

```
nodeLinker: node-modules
```

Or disable eslint-plugin-import.

**Comment by Toilal** [comment]
Yarn PnP is strict about module dependencies and a dependency can be imported only if it's declared in the module's package.json.

`eslint-module-utils` package.json doesn't declare `eslint-import-resolver-typescript` as a dependency or peerDependency, so it can't import it.

It's possible to manually extend any `package.json` of dependencies in `.yarnrc.yml` though:

```
packageExtensions:
  "eslint-module-utils@*":
    dependencies:
      "eslint-import-resolver-typescript": "*"
``` 

This configuration seems to be the best workaround for the issue.

**Comment by ljharb** [comment]
If something that works with npm doesn't work with yarn PnP, then yarn PnP is broken, not "strict". Nothing needs fixing here.

Additionally, if you're using PnP, you're using a different resolution algorithm than node has, and so you shouldn't be using the node resolver or even perhaps the typescript resolver, but rather a PnP-specific resolver (which I'm not sure exists)
