### ISSUE TITLE
WSL Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by AndyOGo** [import-js/eslint-plugin-import#2737]
All jobs with **WSL** config fail on `master`.
https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46338908

E.g.:
https://ci.appveyor.com/project/ljharb/eslint-plugin-import/builds/46338908/job/hqyre5h5sbfqqn44
````sh
Error: Cannot find module 'semver'
Require stack:
- /mnt/c/projects/eslint-plugin-import/tests/src/cli.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/index.js
- /mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
    at Function.Module._load (node:internal/modules/cjs/loader:866:27)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/tests/src/cli.js:9:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.replacementCompile (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at loader (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.<computed> (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Module.replacementCompile (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at require.extensions.<computed> (/mnt/c/projects/eslint-plugin-import/node_modules/babel-register/lib/node.js:152:7)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at runMain (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:68:10)
    at Function.<anonymous> (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:171:5)
    at Object.<anonymous> (/mnt/c/projects/eslint-plugin-import/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at /home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:178:8
    at Object.<anonymous> (/home/appveyor/.node-spawn-wrap-41-9e09463faa5b/node:181:3)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/projects/eslint-plugin-import/tests/src/cli.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/lib/mocha.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/index.js',
    '/mnt/c/projects/eslint-plugin-import/node_modules/mocha/bin/_mocha'
  ]
}
````

**Comment by ljharb** [comment]
I'm aware of this, but I'm not sure what's causing it. I'd love a PR that can fix it (or alternatively, migrate windows tests to GHA).

**Comment by AndyOGo** [comment]
`mocha` seems to make use of it.

I found an issue over there from 2019, which is closed
https://github.com/mochajs/mocha/issues/3868

**Comment by AndyOGo** [comment]
I cloned `mocha` and checked out the `v3.5.3` tag

```sh
npm ls semver
mocha@3.5.3 /mocha
├─┬ karma@1.3.0
│ └─┬ log4js@0.6.38
│   └── semver@4.3.6
├─┬ nyc@11.9.0
│ ├─┬ istanbul-lib-instrument@1.10.1
│ │ └── semver@5.5.0
│ └─┬ test-exclude@4.2.1
│   └─┬ read-pkg-up@1.0.1
│     └─┬ read-pkg@1.1.0
│       └─┬ normalize-package-data@2.4.0
│         └── semver@5.5.0 deduped
├─┬ os-name@2.0.1
│ └─┬ win-release@1.1.1
│   └── semver@5.7.1
└─┬ phantomjs@1.9.8
  └─┬ npmconf@0.0.24
    └── semver@1.1.4
```

**Comment by AndyOGo** [comment]
I missed the obvious

`semver` is installed and utilized by `no-duplicates`:
https://github.com/import-js/eslint-plugin-import/blob/5680a1f8d41cd19f9c60d999a6fadf10994a0a64/src/rules/no-duplicates.js#L3

**Comment by ljharb** [comment]
Good call, and it's in the project's `dependencies`, so there's no reason it shouldn't be present.

**Comment by AndyOGo** [comment]
Indeed.

I googled that error. These sources suggest that `npm` is mesed up somehow and to re-install it.
I can only guess.
Do you have access to try that?
- https://github.com/npm/node-semver/issues/205
- https://stackoverflow.com/questions/33870520/npm-install-cannot-find-module-semver
- https://askubuntu.com/questions/1152570/npm-cant-find-module-semver-error-in-ubuntu-19-04
- https://superuser.com/questions/1438196/npm-error-cannot-find-module-semver/1438491#1438491

**Comment by ljharb** [comment]
All of that is handled in appveyor.yml - PRs are quite welcome :-)

**Comment by AndyOGo** [comment]
I created just a workaround and excluded the remaining WSL jobs.

A proper solution is still required.

**Comment by AndyOGo** [comment]
I understand.
It is what is and has a bitter taste.

**Comment by AndyOGo** [comment]
@ljharb 
I tried to install it via `nvm` as suggested here, but that failed miserably.
https://learn.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#install-nvm-nodejs-and-npm
