### ISSUE TITLE
Plugin crashes ESLint when TypeScript is used

### ISSUE THREAD

**Issue by vekunz** [import-js/eslint-plugin-import#2831]
Hi,

we use eslint-plugin-import for a long time. But now somehow it makes problems. After rebuilding parts of our ESLint configuration, this plugin does not seem to work correctly anymore.

But when I tried to create a reproduction repository, I could not reproduce our issues, because in the reproduction repo, this plugin just crashes the whole eslint process, but I have no idea, what is wrong with the configuration.

```
Oops! Something went wrong! :(

ESLint: 8.45.0

EslintPluginImportResolveError: typescript with invalid interface loaded as resolver
Occurred while linting C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\vite.config.ts:1
Rule: "import/namespace"
    at requireResolver (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\resolve.js:188:17) 
    at fullResolve (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\resolve.js:134:22)     
    at Function.relative (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\resolve.js:84:10)
    at remotePath (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-plugin-import\lib\ExportMap.js:811:379)
    at processDynamicImport (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-plugin-import\lib\ExportMap.js:809:179)
    at Object.ImportExpression (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-plugin-import\lib\ExportMap.js:810:221)
    at visit (C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\visit.js:11:22)
    at C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\visit.js:19:7
    at Array.forEach (<anonymous>)
    at C:\Entwicklung\Sonstiges\_bug_reproductions\svelte-eslint-import\node_modules\eslint-module-utils\visit.js:18:32

Process finished with exit code 2
```

You can find this reproduction repo here https://github.com/vekunz/svelte-eslint-import. The app is the default demo app from SvelteKit, but with a bit of custom ESLint configuration.

**Comment by JounQin** [comment]
You didn't use https://github.com/import-js/eslint-import-resolver-typescript
