### ISSUE TITLE
Error parsing git format in package.json (pnpm)

### ISSUE THREAD

**Issue by nobiit** [import-js/eslint-plugin-import#3020]
If package.json has a package installed from git, it will include sha in the path, and this seems to cause an error with the `import/namespace` rule

Error
```Error
admin@NobiPC ➜ materio git:(develop) ✗ eslint src/db/server/server.ts

Oops! Something went wrong! :(

ESLint: 8.57.0

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '/Users/admin/<user>/<repo>/node_modules/.pnpm/<repo>@git+https+++git@github.com+<user>+<repo>.git\x00#6affeaa31c0e...
Occurred while linting /Users/admin/nobidev/materio/src/db/server/server.ts:1
Rule: "import/namespace"
    at Object.statSync (node:fs:1657:10)
    at ExportMap.for (/Users/admin/nobidev/materio/node_modules/.pnpm/eslint-plugin-import@2.29.1_@typescript-eslint+parser@7.13.0_eslint@8.57.0_typescript@5.4.5___pi7blvkmllwoqjthpibydoafqm/node_modules/eslint-plugin-import/lib/ExportMap.js:802:69)
    at ExportMap.get (/Users/admin/nobidev/materio/node_modules/.pnpm/eslint-plugin-import@2.29.1_@typescript-eslint+parser@7.13.0_eslint@8.57.0_typescript@5.4.5___pi7blvkmllwoqjthpibydoafqm/node_modules/eslint-plugin-import/lib/ExportMap.js:801:465)
    at processBodyStatement (/Users/admin/nobidev/materio/node_modules/.pnpm/eslint-plugin-import@2.29.1_@typescript-eslint+parser@7.13.0_eslint@8.57.0_typescript@5.4.5___pi7blvkmllwoqjthpibydoafqm/node_modules/eslint-plugin-import/lib/rules/namespace.js:11:40)
    at /Users/admin/nobidev/materio/node_modules/.pnpm/eslint-plugin-import@2.29.1_@typescript-eslint+parser@7.13.0_eslint@8.57.0_typescript@5.4.5___pi7blvkmllwoqjthpibydoafqm/node_modules/eslint-plugin-import/lib/rules/namespace.js:84:40
    at Array.forEach (<anonymous>)
    at Program (/Users/admin/nobidev/materio/node_modules/.pnpm/eslint-plugin-import@2.29.1_@typescript-eslint+parser@7.13.0_eslint@8.57.0_typescript@5.4.5___pi7blvkmllwoqjthpibydoafqm/node_modules/eslint-plugin-import/lib/rules/namespace.js:84:18)
    at ruleErrorHandler (/Users/admin/nobidev/materio/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/linter/linter.js:1076:28)
    at /Users/admin/nobidev/materio/node_modules/.pnpm/eslint@8.57.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

Other information:

eslint-plugin-import version `v2.29.1`

```package.json
{
  "dependencies": {
    "<repo>": "<user>/<repo>#<sha>",
  }
}
```

```src/main.ts
import {a,b,c} from '<user>/<repo>';
```

```bash
pnpm install
eslint src/main.ts
```

**Comment by nobiit** [comment]
It seems to be related to this paragraph.


https://github.com/import-js/eslint-plugin-import/blob/main/src/exportMap/builder.js#L52

I think I need to cut off the fragment in the path?

**Comment by nobiit** [comment]
I see a '\x00' character in the path variable. Does it make sense?

**Comment by nobiit** [comment]
I had success with this little patch, it works for me :D

https://github.com/nobiit/eslint-plugin-import/commit/27e886257db3a448a4fb46d16b50b258d156ff45

It seems the problem comes from `eslint-import-resolver-typescript` . I hope if someone sees this problem confirm it (to avoid blame on my part)

**Comment by ljharb** [comment]
It is very very strange to see a null character in any string, especially here.

Can you confirm that eslint-import-resolver-typescript is producing that character? If so, please file an issue there.

**Comment by Plugo-SeongGonGo** [comment]
Hello, I'm facing the same issues and found some possible causes for this issue(producing a null character).
`eslint-import-resolver-typescript` uses `enhanced-resolve` package to resolve paths, and `enhanced-resolve` [escapes `#` character to `\0#`](https://github.com/webpack/enhanced-resolve?tab=readme-ov-file#escaping). It seems like this behavior was introduced to fix [this issue](https://github.com/webpack/enhanced-resolve/pull/255).

**Comment by soryy708** [comment]
Out of scope for `eslint-plugin-import`, should be brought up with `enhanced-resolve` instead.
